### PR TITLE
First requirement

### PR DESCRIPTION
**Pull request by dareddov**
After navigating to the root directory using a web browser, the app display a login page. If the user is logged in, then user listing is being displayed.

You find creditionals in seeds.rb - email: admin@example.com password: Secret99

### CODE REVIEW

**Comment by Exelord** [comment]
Could you add some seeds? I have not any credentials to log in.

Please, remember about instructions when you are creating a PR' with features.

**Review by Exelord — COMMENTED** [review]
The code looks fine

**Comment by Exelord** [comment]
Where can I find tests? Any code styling linter? Rubocop is welcome.
Maybe you should start from TDD, what do you think?

**Comment by Exelord** [comment]
@dareddov 
> Where can I find tests? Any code styling linter? Rubocop is welcome.
Maybe you should start from TDD, what do you think?

**Comment by dareddov** [comment]
@Exelord I will add specs and Rubocop from last PR.

**Comment by dareddov** [comment]
@Exelord Seeds added.

**Comment by Exelord** [comment]
It works, but I have a few minor remarks:
No notification in case of a wrong password. I can not see who is logged in.

**Pull request merged**
