### PR TITLE
Fourth requirement

### PR DESCRIPTION
**Pull request by dareddov**
Admin see a link "Admin Panel" from navbar.

Admin user - email: admin@example.com, password: Secret99 (if you have users from seeds)

### CODE REVIEW

**Comment by Exelord** [comment]
Please, add a description with the test instruction.

**Comment by dareddov** [comment]
@Exelord I updated description PR, please see at this now, thanks. :)

**Review by Exelord — CHANGES_REQUESTED** [review]
After logout :/ 
screen shot 2017-04-04 at 21 30 11

**Comment by dareddov** [comment]
I fix it from the next PR. Can you check it on next PR?

**Review by Exelord — APPROVED** [review]

**Pull request merged**
